config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  get 'welcome/index2'
  get 'users', to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :companies do
      resources :your_comments do
        resources :likes do
          collection do 
            get 'hilike'
            get 'byelike'
          end
        end
      end
    end
    resources :cities do
      resources :citycomments do
       resources :citylikes do
        collection do
          get 'hilike'
          get 'byelike'
        end
      end
    end
  end
    resources :states
    resources :countries
    resources :places
    resources :nodes
    resources :images
    resources :regions
    resources :user_regions
    resources :user_roles
    resources :users
    resources :signups
    resources :my_user
  #get 'user_roles/alluser', 'user_roles#alluser'
  root 'welcome#index2'
  get 'my/profile', :to => 'users#veer', as: :profile
  get 'my/allprofile', :to => 'users#viru', as: :allprofile
  get 'my/show_all_profile_name', :to => 'my_user#show_all_profile_name', as: :show_all_profile_name
  delete 'my/user_destroy/:my_user_id', :to => 'my_user#user_destroy', as: :user_destroy
  get 'my/show_particular_user_profile/:my_user_id', :to => 'my_user#show_particular_user_profile', as: :show_particular_user_profile
  #get 'companies/:companies_id/dislike', :to =>'likes#dislike' , as: :dislike

 end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/city.rb
class City < ApplicationRecord
	has_many :citycomments
end

app/models/citycomment.rb
class Citycomment < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :citylikes
end

app/models/citylike.rb
class Citylike < ApplicationRecord
	belongs_to :citycomment
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
 end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :state
	belongs_to :country
	belongs_to :city
	has_many :your_comments
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord

   mount_uploader :image_name, AvatarUploader

end

app/models/like.rb
class Like < ActiveRecord::Base
    
    belongs_to :your_comment
	belongs_to :user
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/signup.rb
class Signup < ApplicationRecord
	 validates :username, presence: true,
                    length: { minimum: 5 }
       validates :password, presence: true,
                    length: { minimum: 8 }             
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   #mount_uploader :image, UserImageUploader
  # mount_uploader :image, NewImageUploader
   mount_uploader :image, AvatarUploader
    belongs_to :state
	  belongs_to :country
	  belongs_to :city
    has_many :likes, dependent: :destroy
    end

app/models/user_region.rb
class UserRegion < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/your_comment.rb
class YourComment < ApplicationRecord
  belongs_to :company
  has_many :likes, dependent: :destroy
end

app/controllers/citycomments_controller.rb
class CitycommentsController < ApplicationController

	  def create
	      @city = City.find(params[:city_id])
	      @citycomment = @city.citycomments.create(citycomment_params)
	     # redirect_to city_path(@city)
	  end

	  def destroy
	    @city = City.find(params[:city_id])
	    @citycomment = @city.citycomments.find(params[:id])
	    @citycomment.destroy
	   ## redirect_to city_path(@city)
	  end
	 
	  private
	    def citycomment_params
	      params.require(:citycomment).permit(:user_id, :body)
	    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/citycomments/_citycomment.html.erb
<% @city.citycomments.each do |citycomment| %>
    <% if !(citycomment.id == nil) %>
	       <%= render 'citycomments/comment', comment: citycomment %>
     <% end %>
<% end %>

app/views/citycomments/_comment.html.erb
<% if comment.present? %>
 
    <div id="comment-<%= comment.id %>">
       <p>
	      <strong>Commenter:</strong>
	      <%= comment.user.try(:first_name) %>
	   </p>
	 
	   <p>
	       <strong>Comment:</strong>
	       <%= comment.body %>
	   </p>
     	
 <div id="viru-<%= comment.id %>">
		<%= render 'citycomments/like_dislike', comment: comment, city: @city %>
	</div>

<div>
	  <%= link_to 'Delete Comment', [comment.city, comment], method: :delete, data: { confirm: 'Are you sure?' , remote: true} %>
	</div>


    </div>
     <hr>
<% end -%>

app/views/citycomments/_form.html.erb
<%= form_with(model: [@city, @city.citycomments.build ] , remote: true, id:"do-nothing") do |form| %>

   <p>
       <%= form.hidden_field :user_id, value: current_user.id %>
   </p>

   <p>
      <%= form.label :body %><br>
      <%= form.text_area :body, required: true %>
   </p>

   <p>
      <%= form.submit 'submit' %>
   </p>

<% end %>

app/views/citycomments/_like_dislike.html.erb
<% if Citylike.where(citycomment_id: comment.id, user_id: current_user.id).any? %>
<%# comment =Comment.last %>
   <%= link_to 'Unlike', byelike_city_citycomment_citylikes_path(city,comment), remote: true%>

   <% else %>
   <%# comment =Comment.last %>
     <%= link_to 'Like', hilike_city_citycomment_citylikes_path(city,comment), remote: true %>
   <% end %>

	<p><%= comment.citylikes.count %> 
	<%= (comment.citylikes.count) == 0 ? 'like' : 'likes'%></p>

app/views/citycomments/create.js.erb
$('#viru-name').append('<%= j render "citycomments/comment",comment:@citycomment %>');
$("form#do-nothing")[0].reset();

app/views/citycomments/destroy.js.erb
$('#viru-<%= @citycomment.id %>').remove()