config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  get 'welcome/index2'
  get 'users', to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :companies do
      resources :your_comments do
        resources :likes do
          collection do 
            get 'hilike'
            get 'byelike'
          end
        end
      end
    end
    resources :cities do
      resources :citycomments do
       resources :citylikes do
        collection do
          get 'hilike'
          get 'byelike'
        end
      end
    end
  end
    resources :states
    resources :countries
    resources :places
    resources :nodes
    resources :images
    resources :regions
    resources :user_regions
    resources :user_roles
    resources :users
    resources :signups
    resources :my_user
  #get 'user_roles/alluser', 'user_roles#alluser'
  root 'welcome#index2'
  get 'my/profile', :to => 'users#veer', as: :profile
  get 'my/allprofile', :to => 'users#viru', as: :allprofile
  get 'my/show_all_profile_name', :to => 'my_user#show_all_profile_name', as: :show_all_profile_name
  delete 'my/user_destroy/:my_user_id', :to => 'my_user#user_destroy', as: :user_destroy
  get 'my/show_particular_user_profile/:my_user_id', :to => 'my_user#show_particular_user_profile', as: :show_particular_user_profile
  #get 'companies/:companies_id/dislike', :to =>'likes#dislike' , as: :dislike

 end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/city.rb
class City < ApplicationRecord
	has_many :citycomments
end

app/models/citycomment.rb
class Citycomment < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :citylikes
end

app/models/citylike.rb
class Citylike < ApplicationRecord
	belongs_to :citycomment
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
 end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :state
	belongs_to :country
	belongs_to :city
	has_many :your_comments
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord

   mount_uploader :image_name, AvatarUploader

end

app/models/like.rb
class Like < ActiveRecord::Base
    
    belongs_to :your_comment
	belongs_to :user
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/signup.rb
class Signup < ApplicationRecord
	 validates :username, presence: true,
                    length: { minimum: 5 }
       validates :password, presence: true,
                    length: { minimum: 8 }             
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   #mount_uploader :image, UserImageUploader
  # mount_uploader :image, NewImageUploader
   mount_uploader :image, AvatarUploader
    belongs_to :state
	  belongs_to :country
	  belongs_to :city
    has_many :likes, dependent: :destroy
    end

app/models/user_region.rb
class UserRegion < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/your_comment.rb
class YourComment < ApplicationRecord
  belongs_to :company
  has_many :likes, dependent: :destroy
end

app/controllers/your_comments_controller.rb
class YourCommentsController < ApplicationController

	def create
      @company = Company.find(params[:company_id])
      @your_comment = @company.your_comments.create(your_comment_params)
      # redirect_to company_path(@company)
  end

  def destroy
    @company = Company.find(params[:company_id])
    @your_comment = @company.your_comments.find(params[:id])
    @your_comment.destroy
   # redirect_to company_path(@company)
  end
 
  private
    def your_comment_params
      params.require(:your_comment).permit(:commenter, :body)
    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/your_comments_helper.rb
module YourCommentsHelper
end

app/views/your_comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
	<p>
	  <strong>Commenter:</strong>
	  <%= comment.commenter %>
	</p>
	 
	<p>
	  <strong>Comment:</strong>
	  <%= comment.body %>
	</p>

	<div id="any-name-<%= comment.id %>">
		<%= render 'your_comments/like_dislike', comment: comment, company: @company %>
	</div>



	<div id="type-any-name">
	  <%= link_to 'Delete Comment', [comment.company, comment], method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
	</div>
	<hr>
</div>

app/views/your_comments/_form.html.erb
<%= form_with(model: [ @company, @company.your_comments.build ], remote: true, id: "create-comment-form") do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>


<% end %>

app/views/your_comments/_like_dislike.html.erb
<% if Like.where(your_comment_id: comment.id, user_id: current_user.id).any? %>

   <%= link_to 'Unlike', byelike_company_your_comment_likes_path(company,comment), remote: true%>

   <% else %>
     <%= link_to 'Like', hilike_company_your_comment_likes_path(company, comment), remote: true%>
   <% end %>
	
	<p><%= comment.likes.count %> 
	<%= (comment.likes.count) == 0 ? 'like' : 'likes'%></p>

app/views/your_comments/_your_comment.html.erb
<% @company.your_comments.each do |your_comment| %>
<%= render 'your_comments/comment', comment: your_comment %>

<% end %>

app/views/your_comments/create.js.erb
$('#anytype-name').append('<%= j render "your_comments/comment", comment: @your_comment %>');
$("form#create-comment-form")[0].reset();
$("html, body").animate({ scrollTop: $(document).height() }, 1000);

app/views/your_comments/destroy.js.erb
$('#comment-<%= @your_comment.id %>').remove();