config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  get 'welcome/index2'
  get 'users', to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :companies do
      resources :your_comments do
        resources :likes do
          collection do 
            get 'hilike'
            get 'byelike'
          end
        end
      end
    end
    resources :cities do
      resources :citycomments do
       resources :citylikes do
        collection do
          get 'hilike'
          get 'byelike'
        end
      end
    end
  end
    resources :states
    resources :countries
    resources :places
    resources :nodes
    resources :images
    resources :regions
    resources :user_regions
    resources :user_roles
    resources :users
    resources :signups
    resources :my_user
  #get 'user_roles/alluser', 'user_roles#alluser'
  root 'welcome#index2'
  get 'my/profile', :to => 'users#veer', as: :profile
  get 'my/allprofile', :to => 'users#viru', as: :allprofile
  get 'my/show_all_profile_name', :to => 'my_user#show_all_profile_name', as: :show_all_profile_name
  delete 'my/user_destroy/:my_user_id', :to => 'my_user#user_destroy', as: :user_destroy
  get 'my/show_particular_user_profile/:my_user_id', :to => 'my_user#show_particular_user_profile', as: :show_particular_user_profile
  #get 'companies/:companies_id/dislike', :to =>'likes#dislike' , as: :dislike

 end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/city.rb
class City < ApplicationRecord
	has_many :citycomments
end

app/models/citycomment.rb
class Citycomment < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :citylikes
end

app/models/citylike.rb
class Citylike < ApplicationRecord
	belongs_to :citycomment
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
 end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :state
	belongs_to :country
	belongs_to :city
	has_many :your_comments
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord

   mount_uploader :image_name, AvatarUploader

end

app/models/like.rb
class Like < ActiveRecord::Base
    
    belongs_to :your_comment
	belongs_to :user
end

app/models/node.rb
class Node < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/signup.rb
class Signup < ApplicationRecord
	 validates :username, presence: true,
                    length: { minimum: 5 }
       validates :password, presence: true,
                    length: { minimum: 8 }             
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   #mount_uploader :image, UserImageUploader
  # mount_uploader :image, NewImageUploader
   mount_uploader :image, AvatarUploader
    belongs_to :state
	  belongs_to :country
	  belongs_to :city
    has_many :likes, dependent: :destroy
    end

app/models/user_region.rb
class UserRegion < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/your_comment.rb
class YourComment < ApplicationRecord
  belongs_to :company
  has_many :likes, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!

	def index 
		@companies= Company.all
	end

	def show
		@company = Company.find(params[:id])
	end
	
	def new
	end


	def edit
        @company = Company.find(params[:id])
    end

	def create
		@company = Company.new(company_params) 
     @company.user_id = current_user.id
        @company.save
        redirect_to @company
	end  

  def update
    @company = Company.find(params[:id])
   
    if @company.update(company_params)
      redirect_to @company_params
    else
      render 'edit'
    end
  end


  private
    def company_params
      params.require(:company).permit(:name, :country_id, :state_id, :city_id, :postcode, :start_date)
    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/companies/edit.html.erb
<h1> this is edit your company details </h1>
<%= form_with(model: @company, local: true) do |form| %>
 
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@company.errors.count, "error") %> prohibited
        this company from being saved:
      </h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
 </p>

 <p>
  <%= form.label :Country_id %><br>
  <%= form.select :country_id, Country.all.collect { |p| [ p.country_name, p.id ] }, include_blank: true %>
 </p>

 <p>
  <%= form.label :State_id %><br>
  <%= form.select :state_id, State.all.collect { |p| [ p.state_city, p.id ] }, include_blank: true %>
 </p>

 <p>
  <%= form.label :City_id %><br>
  <%= form.select :city_id, City.all.collect { |p| [ p.city_name, p.id ] }, include_blank: true %>
 </p>

 <p>
    <%= form.label :Postcode %><br>
    <%= form.text_field :postcode %>
 </p>

 <p>
    <%= form.label :Start_date %><br>
    <%= form.datetime_select :start_date %>
 </p>

 <p>
   <%= form.label :Active %><br>
   <%= form.check_box :active %>
 </p>

 <p>
    <%= form.submit %>
 </p>
<% end %>
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Country_Id</th>
    <th>State_Id</th>
    <th>City_Id</th>
    <th>Postcode</th>
    <th>Start_date</th>
  </tr>
 
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.country_id %></td>
      <td><%= company.state_id %></td>
      <td><%= company.city_id %></td>
      <td><%= company.postcode %></td>
      <td><%= company.start_date %></td>

      <td>      
      <%= link_to 'Show', company_path(company) %></td>
      <td>
      <% if (company.user_id == current_user.id) %>
      <%= link_to ' Edit ', "/companies/#{company.id}/edit" %>
        <% end %>
      </td>

      
    </tr>
  <% end %>
  <%= link_to 'New company', new_company_path %>
</table>
<%= link_to 'Back', welcome_index_path %>

app/views/companies/new.html.erb
<h1> New company </h1>

<%= form_with scope: :company, url: companies_path, local: true do |form| %>
 <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
 </p>

 <p>
  <%= form.label :Country_id %><br>
  <%= form.select :country_id, Country.all.collect { |p| [ p.country_name, p.id ] }, include_blank: true %>
 </p>

 <p>
  <%= form.label :State_id %><br>
  <%= form.select :state_id, State.all.collect { |p| [ p.state_city, p.id ] }, include_blank: true %>
 </p>

 <p>
  <%= form.label :City_id %><br>
  <%= form.select :city_id, City.all.collect { |p| [ p.city_name, p.id ] }, include_blank: true %>
 </p>

 <p>
    <%= form.label :Postcode %><br>
    <%= form.text_field :postcode %>
 </p>

 <p>
    <%= form.label :Start_date %><br>
    <%= form.datetime_select :start_date %>
 </p>

 <p>
   <%= form.label :Active %><br>
   <%= form.check_box :active %>
 </p>

 <p>
    <%= form.submit %>
 </p>

<% end %>

<%= link_to 'Back', welcome_index_path %>
<br>
<%= link_to 'Show all Registered company', companies_path %>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
 
<p>
  <strong>Country_Id:</strong>
  <%= @company.country.country_name %>
</p>

<p>
  <strong>State_Id:</strong>
  <%= @company.state.state_city %>
</p>
 
<p>
  <strong>City_Id:</strong>
  <%= @company.city.city_name %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @company.postcode %>
</p>
 
<p>
  <strong>Start_date:</strong>
  <%= @company.start_date %>
</p>
<%= link_to 'Edit', edit_company_path%>
<%= link_to 'Back', companies_path %>

<h2>Comments</h2>

<div id="anytype-name">
     <%= render 'your_comments/your_comment' %>
</div>

<h2> Add a comment:</h2>
<%= render 'your_comments/form' %>